Feature/add check for valid credentials
gippy/instagram-scraper pull request #105
Opened 2020-11-25 10:45 UTC by VaclavRut

solving #104 so it will throw error

2020-11-25 16:53 UTC, pocesar commented on src/login.js
> +        await sleep(5000);
this can be changed to a:

```js
await Promise.allSettled([
   page.waitForResponse((response) => response.url().includes('/ajax'), { timeout: 5000 }),
   page.click('button[type="submit"]'),
])
```

2020-11-25 16:55 UTC, pocesar commented on src/login.js
> +        if (invalidCredentials !== null) {
prefer using a boolean here, as in `document.querySelector('#slfErrorAlert') !== null`

2020-11-25 17:34 UTC, pocesar commented on src/login.js
> +        await Apify.setValue('LOGINFAILED_HTML', pageHtml, { contentType: 'text/html' });
maybe change this many lines to use `Apify.utils.puppeteer.saveSnapshot` as it does both

2020-11-26 08:26 UTC, VaclavRut commented on src/login.js
> +        await Apify.setValue('LOGINFAILED_HTML', pageHtml, { contentType: 'text/html' });
updated, only it will not save the JPEG, only HTML now.
Also that Promise.allSettled() doesn't seem to do the job, it will  not throw the error after the update.

2020-11-26 16:09 UTC, pocesar commented on src/login.js
> +        await Apify.setValue('LOGINFAILED_HTML', pageHtml, { contentType: 'text/html' });
yeah allSettled doesn't throw, it sets the result status to `fulfilled` or `rejected`, if you need to check for the timeout

2020-11-26 16:49 UTC, pocesar commented on src/login.js
> +        await Apify.setValue('LOGINFAILED_HTML', pageHtml, { contentType: 'text/html' });
oh, the click is duplicated and awaiting at the top 

```js
        await page.click('button[type="submit"]'); // remove this line

        await Promise.allSettled([
            page.waitForResponse((response) => response.url().includes('/ajax'), { timeout: 5000 }),
            page.click('button[type="submit"]'),
        ]);
```

2020-11-26 16:50 UTC, pocesar requested changes
removing the duplicate await click should do it

2020-12-08 11:17 UTC, VaclavRut commented
Can you test it @pocesar ?
```
{
    "searchType": "user",
    "directUrls": [
        "https://www.instagram.com/gali_givati/"
    ],
    "resultsType": "details",
    "proxy": {
        "useApifyProxy": true,
        "apifyProxyGroups": []
    },
    "loginUsername": "kokoko",
    "loginPassword": "123123",
    "followingLimit": 0,
    "followedByLimit": 5,
    "expandOwners": false,
    "useStealth": false,
    "includeHasStories": false,
    "extendOutputFunction": "($) => { return {} }",
    "searchLimit": 10,
    "resultsLimit": 200,
    "maxRequestRetries": 5,
    "scrollWaitSecs": 15,
    "maxErrorCount": 3,
    "cookiesPerConcurrency": 0,
    "likedByLimit": 0,
    "maxConcurrency": 1000
}

```

2020-12-08 15:23 UTC, merged